version: '3.1'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    
  api:
    build:
      context: .
      target: builder
    command: go run .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URI: postgres://postgres:secret@db:5432/test?sslmode=disable
